conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, include
)

from conf.views import HomeView

urlpatterns = [
    path('',
         HomeView.as_view(), name='home'),

    path('admin/',
         admin.site.urls),

    path('i18n/',
         include('django.conf.urls.i18n')),

    path('accounts/',
         include('member.urls')),

    path('golf/',
         include('golf.urls', namespace='golf')),

    path('timesheet/',
         include('timesheet.urls', namespace='timesheet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

golf/urls.py
from django.urls import path

from . import views

app_name = 'golf'

urlpatterns = [
    # Agency
    path('agency/booking/',
         views.AgencyBookingListView.as_view(), name="agency-booking-list"),

    path('agency/booking/create',
         views.AgencyBookingCreateView.as_view(), name="agency-booking-create"),

    path('agency/booking/<uuid:uuid>/',
         views.AgencyBookingDetailView.as_view(), name='agency-booking-detail'),

    path('agency/booking/<uuid:uuid>/change',
         views.AgencyBookingChangeUpdateView.as_view(), name='agency-booking-change'),

    path('agency/booking/<uuid:uuid>/accept',
         views.AgencyBookingAcceptUpdateView.as_view(), name='agency-booking-accept'),

    path('agency/booking/<uuid:uuid>/revoke',
         views.AgencyBookingRevokeUpdateView.as_view(), name='agency-booking-revoke'),

    path('agency/booking/<uuid:uuid>/delete/',
         views.AgencyBookingDeleteView.as_view(), name='agency-booking-delete'),

    # Staff
    path('staff/booking/',
         views.StaffBookingListView.as_view(), name="staff-booking-list"),

    path('staff/booking/<uuid:uuid>/',
         views.StaffBookingDetailView.as_view(), name='staff-booking-detail'),

    path('staff/booking/<uuid:uuid>/accept',
         views.StaffBookingAcceptUpdateView.as_view(), name='staff-booking-accept'),

    path('staff/booking/<uuid:uuid>/confirm',
         views.StaffBookingConfirmUpdateView.as_view(), name='staff-booking-confirm'),

    path('staff/booking/<uuid:uuid>/offer',
         views.StaffBookingOfferUpdateView.as_view(), name='staff-booking-offer'),

    path('staff/booking/<uuid:uuid>/void',
         views.StaffBookingVoidUpdateView.as_view(), name='staff-booking-void'),

    # AJAX APIs
    path('api/fee/',
         views.APIFeeView.as_view(), name='api-fee'),

    path('api/tee-off-time/add/',
         views.APITeeOffTimeAddView.as_view(), name='api-tee-off-time-add'),

    path('api/tee-off-time/delete/',
         views.APITeeOffTimeDeleteView.as_view(), name='api-tee-off-time-delete'),

    path('api/tee-off-time/accept/',
         views.APITeeOffTimeAcceptView.as_view(), name='api-tee-off-time-accept'),
]

member/urls.py
from importlib import import_module

from allauth.socialaccount import providers
from django.urls import (
    path, re_path
)

from . import views

urlpatterns = [
    # Account
    path('login/',
         views.MemberLoginView.as_view(), name="account_login"),
    path('logout/',
         views.MemberLogoutView.as_view(), name="account_logout"),
    path('signup/',
         views.MemberSignupView.as_view(), name="account_signup"),
    path('inactive/',
         views.MemberAccountInactiveView.as_view(), name="account_inactive"),
    path('unregister/',
         views.MemberUnregisterView.as_view(), name="account_unregister"),

    # Password Change
    path('password/change/',
         views.MemberPasswordChangeView.as_view(), name="account_change_password"),
    path('password/set/',
         views.MemberPasswordSetView.as_view(), name="account_set_password"),

    # Password Reset
    path('password/reset/',
         views.MemberPasswordReset.as_view(), name="account_reset_password"),
    path('password/reset/done/',
         views.MemberPasswordResetDoneView.as_view(), name="account_reset_password_done"),
    re_path(r'^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$',
            views.MemberPasswordResetFromKeyView.as_view(), name="account_reset_password_from_key"),
    path('password/reset/key/done/',
         views.MemberPasswordResetFromKeyDoneView.as_view(), name="account_reset_password_from_key_done"),

    # Email Confirmation
    path('confirm-email/',
         views.MemberEmailVerificationSentView.as_view(), name="account_email_verification_sent"),
    re_path(r'^confirm-email/(?P<key>[-:\w]+)/$',
            views.MemberConfirmEmailView.as_view(), name="account_confirm_email"),
    path('email/',
         views.MemberEmailView.as_view(), name="account_email"),

    # Social Providers
    path('social/login/cancelled/',
         views.MemberSocialLoginCancelledView.as_view(), name='socialaccount_login_cancelled'),
    path('social/login/error/',
         views.MemberSocialLoginErrorView.as_view(), name='socialaccount_login_error'),
    path('social/signup/',
         views.MemberSocialSignupView.as_view(), name='socialaccount_signup'),
    path('social/connections/',
         views.MemberSocialConnectionsView.as_view(), name='socialaccount_connections'),

    # Profile
    path('profile/',
         views.MemberProfileView.as_view(), name="account_profile"),
    path('profile/logs/',
         views.MemberLoginLogView.as_view(), name="account_login_log"),
    path('profile/organization/',
         views.MemberOrganizationCreateView.as_view(), name="account_organization"),

]

# URL patterns for social providers
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

golf/models.py
import re
import uuid

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils import models  as model_utils_models


class Holiday(model_utils_models.TimeStampedModel):
    COUNTRY_CHOICES = Choices(
        (1, 'thailand', _('Thailand')),
        (2, 'south_korea', _('South Korea')),
        (3, 'japan', _('Japan')),
        (4, 'china', _('China')),
    )

    title = models.CharField(
        verbose_name=_('Holiday name'),
        max_length=255,
    )

    holiday = models.DateField(
        verbose_name=_('Holiday day'),
        db_index=True,
    )

    country = models.IntegerField(
        verbose_name=_('Country code'),
        choices=COUNTRY_CHOICES,
        default=COUNTRY_CHOICES.thailand,
        db_index=True,
    )

    class Meta:
        verbose_name = _('Holiday')
        verbose_name_plural = _('Holidays')

        unique_together = ('holiday', 'country')

    def __str__(self):
        return '{} {} {}'.format(self.title, self.holiday, self.country)


class Agency(model_utils_models.TimeStampedModel):
    AGENCY_TYPE_CHOICES = Choices(
        (0, 'travel', _('Travel agency')),
        (1, 'personal', _('Personal agent')),
        (2, 'booking', _('Booking agency')),
    )

    title = models.CharField(
        verbose_name=_('Agency name'),
        max_length=255,
    )

    agency_type = models.IntegerField(
        verbose_name=_('Agency type'),
        choices=AGENCY_TYPE_CHOICES,
        default=AGENCY_TYPE_CHOICES.travel,
        db_index=True,
    )

    bank_account = models.CharField(
        verbose_name=_('Bank account'),
        max_length=255,
        blank=True,
        null=True,
    )

    cancellable_days = models.IntegerField(
        verbose_name=_('Cancellable days'),
        db_index=True,
        default=3,
    )

    due_days = models.IntegerField(
        verbose_name=_('Payment due days'),
        db_index=True,
        default=1,
    )

    bookable_days = models.IntegerField(
        verbose_name=_('Bookable days'),
        db_index=True,
        default=90,
    )

    phone = models.CharField(
        verbose_name=_('Phone number'),
        max_length=16,
    )

    email = models.EmailField(
        verbose_name=_('Email address'),
        max_length=255,
    )

    website = models.URLField(
        verbose_name=_('Website'),
        max_length=255,
        blank=True,
        null=True,
    )

    memo = models.TextField(
        verbose_name=_('Memo'),
        help_text=_('A short description'),
        blank=True,
        null=True,
    )

    products = models.ManyToManyField(
        'golf.ClubProductListMembership',
        through='golf.AgencyClubProductListMembership'
    )

    class Meta:
        verbose_name = _('Agency')
        verbose_name_plural = _('Agencies')

    def __str__(self):
        return '{} {} {}'.format(self.title, self.email, self.phone)


class ClubProduct(model_utils_models.TimeStampedModel):
    SEASON_CHOICES = Choices(
        (0, 'low', _('Low season')),
        (1, 'high', _('High season')),
    )

    DAY_CHOICES = Choices(
        (0, 'weekday', _('Weekday')),
        (1, 'weekend', _('Weekend')),
    )

    SLOT_CHOICES = Choices(
        (0, 'morning', _('Morning')),
        (1, 'daytime', _('Daytime')),
        (2, 'twilight', _('Twilight')),
        (3, 'night', _('Night')),
    )

    season = models.IntegerField(
        verbose_name=_('High/Low Season'),
        choices=SEASON_CHOICES,
        default=SEASON_CHOICES.high,
        db_index=True,
    )

    day_of_week = models.IntegerField(
        verbose_name=_('Day of week'),
        choices=DAY_CHOICES,
        default=DAY_CHOICES.weekday,
        db_index=True,
    )

    slot = models.IntegerField(
        verbose_name=_('Time slot'),
        choices=SLOT_CHOICES,
        default=SLOT_CHOICES.morning,
        db_index=True,
    )

    class Meta:
        verbose_name = _('Golf club product')
        verbose_name_plural = _('Golf club products')

        unique_together = ('season', 'day_of_week', 'slot')

    def __str__(self):
        return '{} / {} / {}'.format(
            self.SEASON_CHOICES[self.season],
            self.DAY_CHOICES[self.day_of_week],
            self.SLOT_CHOICES[self.slot],
        )


class Club(model_utils_models.TimeStampedModel):
    HOLE_CHOICES = Choices(
        (0, 'eighteen', _('18 Holes')),
        (1, 'nine', _('9 Holes')),
        (2, 'twentyseven', _('27 Holes')),
        (3, 'thirtysix', _('36 Holes')),
    )

    COUNTRY_CHOICES = Choices(
        (1, 'thailand', _('Thailand')),
        (2, 'south_korea', _('South Korea')),
        (3, 'japan', _('Japan')),
        (4, 'china', _('China')),
    )

    title = models.CharField(
        verbose_name=_('Golf club name'),
        max_length=255,
    )

    phone = models.CharField(
        verbose_name=_('Phone number'),
        max_length=16,
        blank=True,
        null=True,
    )

    email = models.EmailField(
        verbose_name=_('Email address'),
        max_length=255,
        blank=True,
        null=True,
    )

    website = models.URLField(
        verbose_name=_('Website'),
        max_length=255,
        blank=True,
        null=True,
    )

    hole = models.IntegerField(
        verbose_name=_('No. of holes'),
        choices=HOLE_CHOICES,
        default=HOLE_CHOICES.eighteen,
        db_index=True,
    )

    cart_rental_required = models.BooleanField(
        verbose_name=_('Cart rental required'),
        default=False,
        db_index=True,
    )

    cart_fee = models.DecimalField(
        verbose_name=_('Cart fee'),
        max_digits=11,
        decimal_places=2,
        help_text=_('THB'),
    )

    caddie_fee = models.DecimalField(
        verbose_name=_('Caddie fee'),
        max_digits=11,
        decimal_places=2,
        help_text=_('THB'),
    )

    high_season = models.IntegerField(
        verbose_name=_('High season'),
        default=0x0C03,  # b'110000000011'
    )

    max_high_weekday = models.PositiveIntegerField(
        verbose_name=_('Max # of High/Weekday'),
        default=0,
    )

    max_high_weekend = models.PositiveIntegerField(
        verbose_name=_('Max # of High/Weekend'),
        default=0,
    )

    max_low_weekday = models.PositiveIntegerField(
        verbose_name=_('Max # of Low/Weekday'),
        default=0,
    )

    max_low_weekend = models.PositiveIntegerField(
        verbose_name=_('Max # of Low/Weekend'),
        default=0,
    )

    country = models.IntegerField(
        verbose_name=_('Country code'),
        choices=COUNTRY_CHOICES,
        default=COUNTRY_CHOICES.thailand,
        db_index=True,
    )

    products = models.ManyToManyField(
        'golf.ClubProduct',
        through='golf.ClubProductListMembership'
    )

    class Meta:
        verbose_name = _('Golf club')
        verbose_name_plural = _('Golf clubs')

    def __str__(self):
        return '{} {} {}'.format(self.title, self.email, self.phone)


class ClubProductListMembership(models.Model):
    club = models.ForeignKey(
        'golf.Club',
        verbose_name=_('Golf club'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    product_list = models.ForeignKey(
        'golf.ClubProduct',
        verbose_name=_('Product list'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    start_time = models.TimeField(
        verbose_name=_('Start time'),
    )

    end_time = models.TimeField(
        verbose_name=_('End time'),
    )

    list_price = models.DecimalField(
        verbose_name=_('List price'),
        max_digits=11,
        decimal_places=2,
        help_text=_('THB'),
    )

    position = models.IntegerField(
        verbose_name=_('Position'),
    )

    class Meta:
        verbose_name = _('Product list membership')
        verbose_name_plural = _('Product list membership')

        unique_together = ('club', 'product_list')

    def __str__(self):
        return '{} - {}'.format(self.club.title, self.product_list)


class AgencyClubProductListMembership(models.Model):
    agency = models.ForeignKey(
        'golf.Agency',
        verbose_name=_('Agency'),
        db_index=True,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    product_list = models.ForeignKey(
        'golf.ClubProductListMembership',
        verbose_name=_('Product list'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    fee = models.DecimalField(
        verbose_name=_('Fee amount'),
        max_digits=11,
        decimal_places=2,
        help_text=_('THB'),
    )

    position = models.IntegerField(
        verbose_name=_('Position'),
    )

    class Meta:
        verbose_name = _('Agency product list membership')
        verbose_name_plural = _('Agency product list membership')

        unique_together = ('agency', 'product_list')

    def __str__(self):
        return '{} {}'.format(self.agency.title, self.product_list)


class AgentProfile(model_utils_models.TimeStampedModel):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        db_index=True,
        on_delete=models.CASCADE,
    )

    agency = models.ForeignKey(
        'golf.Agency',
        verbose_name=_('Agency'),
        db_index=True,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    cellphone = models.CharField(
        verbose_name=_('Cellphone number'),
        max_length=16,
        blank=True,
        null=True,
    )

    line_id = models.CharField(
        verbose_name=_('Line ID'),
        max_length=32,
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _('Agent profile')
        verbose_name_plural = _('Agent profiles')

    def __str__(self):
        return '{} {} {}'.format(self.user.email, self.user.username, self.cellphone)

member/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel


class LoginLog(TimeStampedModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('user'),
        null=True,
        blank=True,
        editable=True,
        on_delete=models.SET_NULL,
    )

    ip_address = models.GenericIPAddressField(
        verbose_name=_('IP address'),
    )

    class Meta:
        verbose_name = _('Login log')
        verbose_name_plural = _('Login logs')

    def __str__(self):
        return '{} {} {}'.format(self.user.email, self.ip_address, self.created)


class EmailBanned(TimeStampedModel):
    email = models.EmailField(
        verbose_name=_('Email address'),
    )

    class Meta:
        verbose_name = _('Banned Email Address')
        verbose_name_plural = _('Banned Email Addresses')

    def __str__(self):
        return '{} {}'.format(self.email, self.created)


class OrganizationApplication(TimeStampedModel):
    STATUS_CHOICES = Choices(
        (0, 'pending', _('Pending')),
        (1, 'complete', _('Complete')),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('user'),
        editable=True,
        on_delete=models.CASCADE,
    )

    message = models.TextField(
        verbose_name=_('Message'),
    )

    status = models.IntegerField(
        verbose_name=_('Status'),
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.pending,
        db_index=True,
    )

    class Meta:
        verbose_name = _('Organization application')
        verbose_name_plural = _('Organization applications')

    def __str__(self):
        return '{} {}'.format(self.user.id, self.created)

golf/templates/golf/_booking_detail.html
{% load i18n %}

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_status">
            {% trans 'Status / Created' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field has-addons">
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       value="{{ booking.get_status_display }}"
                       class="input disabled"
                       id="id_status"
                       disabled>
                <span class="icon is-small is-left"><i class="fas fa-splotch fa-fw has-text-grey"></i></span>
            </div>
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       value="{{ booking.created|date:'Y-m-d H:i' }}"
                       class="input disabled"
                       id="id_status"
                       disabled>
                <span class="icon is-small is-left"><i class="fas fa-map-pin fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_agent">
            {% trans 'Agency / Agent' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field has-addons">
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       value="{{ booking.agency.title }}"
                       class="input disabled"
                       id="id_agent"
                       disabled>
                <span class="icon is-small is-left"><i class="fas fa-building fa-fw has-text-grey"></i></span>
            </div>
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       value="{{ booking.agent.agentprofile.fullname }}"
                       class="input disabled"
                       id="id_agent"
                       disabled>
                <span class="icon is-small is-left"><i class="fas fa-address-card fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_club">
            {% trans 'Golf club' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field">
            <div class="control has-icons-left">
                <input type="text"
                       value="{{ booking.club.title }}"
                       class="input disabled"
                       id="id_club" disabled>
                <span class="icon is-small is-left"><i class="fas fa-golf-ball fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_round_date">
            {% trans 'Round date/time' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field">
            <div class="control has-icons-left">
                <input type="text"
                       value="{{ booking.round_date|date:'Y-m-d' }}"
                       class="input disabled"
                       id="id_round_date" disabled>
                <span class="icon is-small is-left"><i class="fas fa-calendar-alt fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_slot">
            {% trans 'Time slot' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field has-addons">
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       value="{{ booking.get_slot_display }}"
                       class="input disabled"
                       id="id_slot" disabled>
                <span class="icon is-small is-left"><i class="fas fa-cloud-sun fa-fw has-text-grey"></i></span>
            </div>
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       value="{{ booking.round_time|date:'H:i' }}"
                       class="input disabled"
                       id="id_slot" disabled>
                <span class="icon is-small is-left"><i class="fas fa-clock fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

{% if booking.status == booking.STATUS_CHOICES.order_pending or booking.status == booking.STATUS_CHOICES.offered %}
    {% if form.tee_off_time_hour and form.tee_off_time_minute %}
        <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label" for="{{ form.tee_off_time_hour.id_for_label }}">
                    {{ form.tee_off_time_hour.label }}
                    <span class="has-text-danger">*</span>
                </label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="field has-addons">
                        <div class="control is-expanded has-icons-left">
                            {{ form.tee_off_time_hour }}
                            <span class="icon is-small is-left"><i class="fas fa-clock fa-fw has-text-grey"></i></span>
                        </div>
                        <div class="control is-expanded has-icons-left">
                            {{ form.tee_off_time_minute }}
                        </div>
                    </div>
                    {% if form.tee_off_time_hour.errors or form.tee_off_time_minute.errors %}
                        <p class="help is-danger">
                            {% for error in form.tee_off_time_hour.errors %}
                                {{ error|escape }}
                            {% endfor %}
                            {% for error in form.tee_off_time_minute.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}
{% elif booking.status == booking.STATUS_CHOICES.payment_pending and booking.tee_off_time %}
    <div class="field is-horizontal">
        <div class="field-label is-normal">
            <label class="label" for="id_slot">
                {% trans 'Tee-off time' %}
            </label>
        </div>
        <div class="field-body">
            <div class="field">
                <div class="control has-icons-left">
                    <input type="text"
                           value="{{ booking.tee_off_time|date:'H:i' }}"
                           class="input has-text-dark has-background-warning"
                           id="id_slot" disabled>
                    <span class="icon is-small is-left"><i class="fas fa-clock fa-fw has-text-grey"></i></span>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_people">
            {% trans 'No. of people' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field">
            <div class="control has-icons-left">
                <input type="text"
                       value="{{ booking.people }}"
                       class="input disabled"
                       id="id_people" disabled>
                <span class="icon is-small is-left"><i class="fas fa-users fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_first_name">
            {% trans 'Full name (Passport)' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field">
            <div class="control has-icons-left">
                <input type="text"
                       value="{{ booking.fullname }}"
                       class="input disabled"
                       id="id_people" disabled>
                <span class="icon is-small is-left"><i class="fas fa-id-card fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_fee">
            {% trans 'Fee' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field has-addons">
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       class="input has-text-dark has-background-warning"
                       id="id_fee"
                       value="{{ booking.fee }}"
                       disabled>
                <span class="icon is-small is-left"><i class="fas fa-credit-card fa-fw has-text-grey"></i></span>
            </div>
            <div class="control is-expanded has-icons-left">
                <input type="text"
                       class="input has-text-dark has-background-warning"
                       id="id_fee"
                       value="{{ booking.get_season_display }} / {{ booking.get_day_of_week_display }}"
                       disabled>
                <span class="icon is-small is-left"><i class="fas fa-tasks fa-fw has-text-grey"></i></span>
            </div>
        </div>
    </div>
</div>

<div class="field is-horizontal">
    <div class="field-label is-normal">
        <label class="label" for="id_memo">
            {% trans 'Memo' %}
        </label>
    </div>
    <div class="field-body">
        <div class="field">
            <div class="control has-icons-left">
                <textarea cols="40" rows="10"
                          placeholder="{% trans 'Remarks' %}"
                          class="textarea disabled"
                          id="id_memo" disabled>{{ booking.memo }}</textarea>
            </div>
        </div>
    </div>
</div>

golf/templates/golf/agency_booking_change_update.html
{% extends 'conf/base.html' %}

{% load i18n static %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered">{{ page_title }}</h1>

            <div class="columns is-centered">
                <div class="column is-four-fifths">
                    <form method="post">
                        {% csrf_token %}

                        {% include './_booking_form.html' with form=form booking=booking %}

                        <input type="hidden" id="id_agency" name="agency"
                               value="{{ request.user.agentprofile.agency.id }}">

                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control is-expanded">
                                        <button class="button is-link is-fullwidth" type="submit">
                                            <span class="icon"><i class="fas fa-clipboard-list"></i></span>
                                            <span>{% trans 'Make order' %}</span>
                                        </button>
                                    </div>
                                </div>
                                {% if booking.status == booking.STATUS_CHOICES.order_opened or booking.status == booking.STATUS_CHOICES.voided %}
                                    <div class="field">
                                        <div class="control is-expanded">
                                            <a href="{% url 'golf:agency-booking-delete' booking.booking_uuid %}"
                                               class="button is-danger is-fullwidth">
                                                <span class="icon"><i class="fas fa-trash-alt"></i></span>
                                                <span>{% trans 'Delete order' %}</span>
                                            </a>
                                        </div>
                                    </div>
                                {% endif %}
                                <div class="field">
                                    <div class="control is-expanded">
                                        <a href="{% url 'golf:agency-booking-list' %}"
                                           class="button is-dark is-fullwidth">
                                            <span class="icon"><i class="far fa-list-alt"></i></span>
                                            <span>{% trans 'Order list' %}</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block stylesheet %}
    {{ block.super }}
    <link rel="stylesheet"
          href="{% static "conf/css/vendor/jquery-ui.css" %}">
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript"
            src="{% static "conf/js/vendor/jquery-ui.min.js" %}"></script>
    {% if LANGUAGE_CODE == 'th' %}
        <script type="text/javascript"
                src="{% static "golf/js/datepicker-th.js" %}"></script>
    {% elif LANGUAGE_CODE == 'ko' %}
        <script type="text/javascript"
                src="{% static "golf/js/datepicker-ko.js" %}"></script>
    {% endif %}
    <script type="text/javascript"
            src="{% static "conf/js/csrf-cookie.js" %}"></script>
    <script type="text/javascript"
            src="{% static "golf/js/booking.js" %}"></script>
{% endblock %}