conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, include
)

from conf.views import HomeView

urlpatterns = [
    path('',
         HomeView.as_view(), name='home'),

    path('admin/',
         admin.site.urls),

    path('i18n/',
         include('django.conf.urls.i18n')),

    path('accounts/',
         include('member.urls')),

    path('golf/',
         include('golf.urls', namespace='golf')),

    path('timesheet/',
         include('timesheet.urls', namespace='timesheet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

member/urls.py
from importlib import import_module

from allauth.socialaccount import providers
from django.urls import (
    path, re_path
)

from . import views

urlpatterns = [
    # Account
    path('login/',
         views.MemberLoginView.as_view(), name="account_login"),
    path('logout/',
         views.MemberLogoutView.as_view(), name="account_logout"),
    path('signup/',
         views.MemberSignupView.as_view(), name="account_signup"),
    path('inactive/',
         views.MemberAccountInactiveView.as_view(), name="account_inactive"),
    path('unregister/',
         views.MemberUnregisterView.as_view(), name="account_unregister"),

    # Password Change
    path('password/change/',
         views.MemberPasswordChangeView.as_view(), name="account_change_password"),
    path('password/set/',
         views.MemberPasswordSetView.as_view(), name="account_set_password"),

    # Password Reset
    path('password/reset/',
         views.MemberPasswordReset.as_view(), name="account_reset_password"),
    path('password/reset/done/',
         views.MemberPasswordResetDoneView.as_view(), name="account_reset_password_done"),
    re_path(r'^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$',
            views.MemberPasswordResetFromKeyView.as_view(), name="account_reset_password_from_key"),
    path('password/reset/key/done/',
         views.MemberPasswordResetFromKeyDoneView.as_view(), name="account_reset_password_from_key_done"),

    # Email Confirmation
    path('confirm-email/',
         views.MemberEmailVerificationSentView.as_view(), name="account_email_verification_sent"),
    re_path(r'^confirm-email/(?P<key>[-:\w]+)/$',
            views.MemberConfirmEmailView.as_view(), name="account_confirm_email"),
    path('email/',
         views.MemberEmailView.as_view(), name="account_email"),

    # Social Providers
    path('social/login/cancelled/',
         views.MemberSocialLoginCancelledView.as_view(), name='socialaccount_login_cancelled'),
    path('social/login/error/',
         views.MemberSocialLoginErrorView.as_view(), name='socialaccount_login_error'),
    path('social/signup/',
         views.MemberSocialSignupView.as_view(), name='socialaccount_signup'),
    path('social/connections/',
         views.MemberSocialConnectionsView.as_view(), name='socialaccount_connections'),

    # Profile
    path('profile/',
         views.MemberProfileView.as_view(), name="account_profile"),
    path('profile/logs/',
         views.MemberLoginLogView.as_view(), name="account_login_log"),
    path('profile/organization/',
         views.MemberOrganizationCreateView.as_view(), name="account_organization"),

]

# URL patterns for social providers
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

timesheet/urls.py
from django.urls import path

from . import views

app_name = 'timesheet'

urlpatterns = [
    path('list/',
         views.TimeSheetListView.as_view(), name="timesheet-list"),
    path('punch-in/',
         views.PunchInCreateView.as_view(), name="timesheet-punch-in"),
    path('punch-out/',
         views.PunchOutUpdateView.as_view(), name="timesheet-punch-out"),
]

timesheet/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils import models  as model_utils_models


class TimeSheet(model_utils_models.SoftDeletableModel, model_utils_models.TimeStampedModel):
    staff = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Staff'),
        db_index=True,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    class Meta:
        verbose_name = _('Time sheet')
        verbose_name_plural = _('Time sheets')

    def __str__(self):
        return '{}-{}'.format(self.staff.first_name, self.staff.last_name)

    @property
    def regular_hours(self):
        return ''

    @property
    def overtime_hours(self):
        return ''

    @property
    def total_hours(self):
        return ''


class PunchLog(model_utils_models.SoftDeletableModel, model_utils_models.TimeStampedModel):
    STATUS_CHOICES = Choices(
        (0, 'punch_in', _('Punch-in')),
        (1, 'punch_out', _('Punch-out')),
    )

    sheet = models.ForeignKey(
        'timesheet.TimeSheet',
        verbose_name=_('Time sheet'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    status = models.IntegerField(
        verbose_name=_('Punch status'),
        choices=STATUS_CHOICES,
        default=STATUS_CHOICES.punch_in,
        db_index=True,
    )

    punch_time = models.DateTimeField(
        verbose_name=_('Punch time'),
    )

    latitude = models.DecimalField(
        verbose_name=_('Punch latitude'),
        max_digits=22,
        decimal_places=16,
    )

    longitude = models.DecimalField(
        verbose_name=_('Punch longitude'),
        max_digits=22,
        decimal_places=16,
    )

    user_agent = models.TextField(
        verbose_name=_('user-agent'),
        blank=True,
    )

    ip_address = models.GenericIPAddressField(
        verbose_name=_('IP address'),
    )

    memo = models.TextField(
        verbose_name=_('Memo'),
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _('Punch log')
        verbose_name_plural = _('Punch logs')

timesheet/forms.py
from django import forms

from . import models


class PunchLogForm(forms.ModelForm):
    latitude = forms.DecimalField(widget=forms.HiddenInput())

    longitude = forms.DecimalField(widget=forms.HiddenInput())

    class Meta:
        model = models.PunchLog
        fields = ()

timesheet/views.py
from decimal import Decimal

from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views import generic
from ipware.ip import get_ip

from golf import viewmixins
from . import forms
from . import models


class TimeSheetListView(viewmixins.PageableMixin, viewmixins.GroupRequiredMixin, generic.ListView):
    group_required = ['staff', ]
    template_name = 'timesheet/timesheet_list.html'
    context_object_name = 'time_list'

    def get_queryset(self):
        queryset = models.TimeSheet.objects.filter(staff__id=self.request.user.id)

        return queryset.order_by('-punch_in_time')

    def get_context_data(self, **kwargs):
        context = super(TimeSheetListView, self).get_context_data(**kwargs)
        context['page_title'] = _('Time sheet')

        return context


class PunchInCreateView(viewmixins.GroupRequiredMixin, generic.CreateView):
    group_required = ['agency', ]
    template_name = 'timesheet/timesheet_create.html'
    form_class = forms.PunchLogForm

    def get_context_data(self, **kwargs):
        context = super(PunchInCreateView, self).get_context_data(**kwargs)
        context['page_title'] = _('Punch-in')
        return context

    def form_valid(self, form):
        sheet = models.TimeSheet()
        sheet.staff = self.request.user
        sheet.save()

        form.instance.sheet = sheet
        form.instance.status = models.PunchLog.STATUS_CHOICES.punch_in

        form.instance.punch_time = timezone.make_aware(timezone.localtime().now())

        form.instance.punch_latitude = Decimal('3.14')
        form.instance.punch_longitude = Decimal('3.14')

        form.instance.user_agent = self.request.META['HTTP_USER_AGENT']
        form.instance.ip_address = get_ip(self.request)

        return super(PunchInCreateView, self).form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super(PunchInCreateView, self).form_invalid(form)

    def get_success_url(self):
        return reverse('timesheet:timesheet-list')


class PunchOutUpdateView(generic.TemplateView):
    template_name = 'timesheet/timesheet_detail.html'

timesheet/templates/timesheet/timesheet_create.html
{% extends 'conf/base.html' %}

{% load i18n static %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered">{{ page_title }}</h1>

            <div class="columns is-centered">
                <div class="column is-four-fifths">
                    <form action="{% url 'timesheet:timesheet-punch-in' %}" method="post" id="punch_form">
                        {% csrf_token %}

                        {% if form.non_field_errors %}
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                </div>
                                <ul class="field-body notification is-danger">
                                    {% for error in form.non_field_errors %}
                                        <li>{{ error|escape }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}

                        {{ form.longitude }}

                        {{ form.latitude }}

                        <div class="field is-horizontal">
                            <div class="field-label is-normal">
                            </div>
                            <div class="field-body">
                                <div class="field">
                                    <div class="control is-expanded">
                                        <button class="button is-link is-fullwidth">
                                            <span class="icon"><i class="fas fa-clipboard-list"></i></span>
                                            <span>{% trans 'Punch-in now' %}</span>
                                        </button>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="control is-expanded">
                                        <a href="{% url 'timesheet:timesheet-list' %}"
                                           class="button is-dark is-fullwidth">
                                            <span class="icon"><i class="far fa-list-alt"></i></span>
                                            <span>{% trans 'Time sheet' %}</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script type="text/javascript"
            src="{% static "conf/js/csrf-cookie.js" %}"></script>
    <script type="text/javascript"
            src="{% static "timesheet/js/punch.js" %}"></script>
{% endblock %}

timesheet/templates/timesheet/timesheet_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
timesheet detail
</body>
</html>

timesheet/templates/timesheet/timesheet_list.html
{% extends 'conf/base.html' %}

{% load i18n static %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}
    <section class="section">
        <div class="container">
            <h1 class="title has-text-centered">{{ page_title }}</h1>

            <div class="columns has-text-weight-bold is-hidden-touch">
                <div class="column is-1">
                    {% trans 'Staff' %}
                </div>
                <div class="column is-1">
                    {% trans 'Punch-in time' %}
                </div>
                <div class="column is-1">
                    {% trans 'Punch-out time' %}
                </div>
                <div class="column is-2">
                    {% trans 'Punch-in location' %}
                </div>
                <div class="column is-2">
                    {% trans 'Punch-out location' %}
                </div>
                <div class="column is-1">
                    {% trans 'Regular hours' %}
                </div>
                <div class="column is-1">
                    {% trans 'Overtime hours' %}
                </div>
                <div class="column is-1">
                    {% trans 'Total hours' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}