conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    path, include
)

from conf.views import HomeView

urlpatterns = [
    path('',
         HomeView.as_view(), name='home'),

    path('admin/',
         admin.site.urls),

    path('i18n/',
         include('django.conf.urls.i18n')),

    path('accounts/',
         include('member.urls')),

    path('golf/',
         include('golf.urls', namespace='golf')),

    path('timesheet/',
         include('timesheet.urls', namespace='timesheet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

golf/urls.py
from django.urls import path

from . import views

app_name = 'golf'

urlpatterns = [
    # Agency
    path('agency/booking/',
         views.AgencyBookingListView.as_view(), name="agency-booking-list"),

    path('agency/booking/create',
         views.AgencyBookingCreateView.as_view(), name="agency-booking-create"),

    path('agency/booking/<uuid:uuid>/',
         views.AgencyBookingDetailView.as_view(), name='agency-booking-detail'),

    path('agency/booking/<uuid:uuid>/change',
         views.AgencyBookingChangeUpdateView.as_view(), name='agency-booking-change'),

    path('agency/booking/<uuid:uuid>/accept',
         views.AgencyBookingAcceptUpdateView.as_view(), name='agency-booking-accept'),

    path('agency/booking/<uuid:uuid>/revoke',
         views.AgencyBookingRevokeUpdateView.as_view(), name='agency-booking-revoke'),

    path('agency/booking/<uuid:uuid>/delete/',
         views.AgencyBookingDeleteView.as_view(), name='agency-booking-delete'),

    # Staff
    path('staff/booking/',
         views.StaffBookingListView.as_view(), name="staff-booking-list"),

    path('staff/booking/<uuid:uuid>/',
         views.StaffBookingDetailView.as_view(), name='staff-booking-detail'),

    path('staff/booking/<uuid:uuid>/accept',
         views.StaffBookingAcceptUpdateView.as_view(), name='staff-booking-accept'),

    path('staff/booking/<uuid:uuid>/confirm',
         views.StaffBookingConfirmUpdateView.as_view(), name='staff-booking-confirm'),

    path('staff/booking/<uuid:uuid>/offer',
         views.StaffBookingOfferUpdateView.as_view(), name='staff-booking-offer'),

    path('staff/booking/<uuid:uuid>/void',
         views.StaffBookingVoidUpdateView.as_view(), name='staff-booking-void'),

    # AJAX APIs
    path('api/fee/',
         views.APIFeeView.as_view(), name='api-fee'),

    path('api/tee-off-time/add/',
         views.APITeeOffTimeAddView.as_view(), name='api-tee-off-time-add'),

    path('api/tee-off-time/delete/',
         views.APITeeOffTimeDeleteView.as_view(), name='api-tee-off-time-delete'),

    path('api/tee-off-time/accept/',
         views.APITeeOffTimeAcceptView.as_view(), name='api-tee-off-time-accept'),
]

member/urls.py
from importlib import import_module

from allauth.socialaccount import providers
from django.urls import (
    path, re_path
)

from . import views

urlpatterns = [
    # Account
    path('login/',
         views.MemberLoginView.as_view(), name="account_login"),
    path('logout/',
         views.MemberLogoutView.as_view(), name="account_logout"),
    path('signup/',
         views.MemberSignupView.as_view(), name="account_signup"),
    path('inactive/',
         views.MemberAccountInactiveView.as_view(), name="account_inactive"),
    path('unregister/',
         views.MemberUnregisterView.as_view(), name="account_unregister"),

    # Password Change
    path('password/change/',
         views.MemberPasswordChangeView.as_view(), name="account_change_password"),
    path('password/set/',
         views.MemberPasswordSetView.as_view(), name="account_set_password"),

    # Password Reset
    path('password/reset/',
         views.MemberPasswordReset.as_view(), name="account_reset_password"),
    path('password/reset/done/',
         views.MemberPasswordResetDoneView.as_view(), name="account_reset_password_done"),
    re_path(r'^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$',
            views.MemberPasswordResetFromKeyView.as_view(), name="account_reset_password_from_key"),
    path('password/reset/key/done/',
         views.MemberPasswordResetFromKeyDoneView.as_view(), name="account_reset_password_from_key_done"),

    # Email Confirmation
    path('confirm-email/',
         views.MemberEmailVerificationSentView.as_view(), name="account_email_verification_sent"),
    re_path(r'^confirm-email/(?P<key>[-:\w]+)/$',
            views.MemberConfirmEmailView.as_view(), name="account_confirm_email"),
    path('email/',
         views.MemberEmailView.as_view(), name="account_email"),

    # Social Providers
    path('social/login/cancelled/',
         views.MemberSocialLoginCancelledView.as_view(), name='socialaccount_login_cancelled'),
    path('social/login/error/',
         views.MemberSocialLoginErrorView.as_view(), name='socialaccount_login_error'),
    path('social/signup/',
         views.MemberSocialSignupView.as_view(), name='socialaccount_signup'),
    path('social/connections/',
         views.MemberSocialConnectionsView.as_view(), name='socialaccount_connections'),

    # Profile
    path('profile/',
         views.MemberProfileView.as_view(), name="account_profile"),
    path('profile/logs/',
         views.MemberLoginLogView.as_view(), name="account_login_log"),
    path('profile/organization/',
         views.MemberOrganizationCreateView.as_view(), name="account_organization"),

]

# URL patterns for social providers
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

conf/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'conf/home.html'

conf/templates/conf/base.html
<!DOCTYPE html>
<html lang="th">
<head>
    {% load static %}
    {% load i18n %}
    {% load member_tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="vxKx8mxChlihmBeKDSEQC8d80w5fumClv2rqebEZ0X8" />
    <title>NaOne : {% block title %}{% endblock %}</title>
    {% block stylesheet %}
        <link rel="stylesheet"
              href="{% static "conf/css/sarabun.css" %}">
        <link rel="stylesheet"
              href="{% static "conf/css/windmill.css" %}">
        <link rel="stylesheet"
              href="{% static "conf/css/base.css" %}">
        <link rel="stylesheet"
              href="//use.fontawesome.com/releases/v5.10.1/css/all.css"
              integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe"
              crossorigin="anonymous">
        <link rel="apple-touch-icon" sizes="180x180"
              href="{% static 'conf/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32"
              href="{% static 'conf/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16"
              href="{% static 'conf/favicon/favicon-16x16.png' %}">
        {{ form.media.css }}
    {% endblock %}
</head>
<body>

{% groups request.user as user_groups %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<div id="gray-background"></div>

<!-- sidenav -->
<nav class="navbar">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'home' %}">
                <img src="{% static 'conf/images/logo.png' %}"
                     width="180" alt="NaOne">
            </a>
            <a class="navbar-burger">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item">
                    Golf clubs
                </a>
                <a class="navbar-item">
                    Hotels
                </a>
                <a class="navbar-item">
                    Transport
                </a>
                <a class="navbar-item">
                    Restaurants
                </a>
            </div>

            <div class="navbar-end">
                {% if not user.is_authenticated %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a href="{% url 'account_login' %}" class="button is-primary">
                                <span class="icon"><i class="fas fa-sign-in-alt fa-fw"></i></span>
                                <span>{% trans 'Sign In' %}</span>
                            </a>
                            <a href="{% url 'account_signup' %}" class="button is-light">
                                <span class="icon"><i class="fas fa-user-plus fa-fw"></i></span>
                                <span>{% trans 'Sign Up' %}</span>
                            </a>
                        </div>
                    </div>
                {% else %}
                    {% if 'agency' in user_groups %}
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                {% trans 'Agency' %}
                            </a>
                            <div class="navbar-dropdown">
                                <a href="{% url 'golf:agency-booking-list' %}" class="navbar-item">
                                    <span class="icon"><i class="fas fa-clipboard-list"></i></span>
                                    <span>{% trans 'Booking management' %}</span>
                                </a>
                            </div>
                        </div>
                    {% elif 'staff' in user_groups %}
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link">
                                {% trans 'Staff' %}
                            </a>
                            <div class="navbar-dropdown">
                                <a href="{% url 'golf:staff-booking-list' %}" class="navbar-item">
                                    <span class="icon"><i class="fas fa-clipboard-list"></i></span>
                                    <span>{% trans 'Booking management' %}</span>
                                </a>
                                <a href="#" class="navbar-item">
                                    <span class="icon"><i class="fas fa-user-cog fa-fw"></i></span>
                                    <span>{% trans 'Agents management' %}</span>
                                </a>
                            </div>
                        </div>
                    {% endif %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            {% trans 'Me' %}
                        </a>
                        <div class="navbar-dropdown">
                            <a href="{% url 'account_profile' %}" class="navbar-item">
                                <span class="icon"><i class="fas fa-user-cog fa-fw"></i></span>
                                <span>{% trans "Profile" %}</span>
                            </a>
                            {% if not user_groups %}
                                <a href="{% url 'account_organization' %}" class="navbar-item">
                                    <span class="icon"><i class="fas fa-building fa-fw"></i></span>
                                    <span>{% trans 'Organization application' %}</span>
                                </a>
                            {% endif %}
                            <hr class="navbar-divider">
                            <a href="{% url 'account_logout' %}" class="navbar-item">
                                <span class="icon"><i class="fas fa-sign-out-alt fa-fw"></i></span>
                                <span>{% trans 'Sign Out' %}</span>
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

<main>{% block content %}{% endblock %}</main>

<footer class="footer has-background-grey-lighter">
    <div class="container">
        <div class="columns">
            <div class="column">
                Copyright &copy; {% now "Y" %} <strong>NaOne</strong>
                All Rights Reserved.
            </div>
            <div class="column has-text-right-tablet">
                <form class="is-inline" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}"/>
                    <div class="select is-small">
                        <select id="language-selector" name="language">
                            {% for language in languages %}
                                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                        selected{% endif %}>
                                    {{ language.name_local }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </form>
            </div>
        </div>
    </div>
</footer>

{% if messages %}
    <div style="display:none">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}
</body>

{% block javascript %}
    <script type="text/javascript"
            src="{% static "conf/js/vendor/jquery-3.4.1.min.js" %}"></script>
    <script type="text/javascript"
            src="{% static "conf/js/base.js" %}"></script>
    {{ form.media.js }}
{% endblock %}
</html>

conf/templates/conf/home.html
{% extends 'conf/base.html' %}

{% block title %}Relax and enjoy your life!{% endblock %}

{% block content %}
    <section class="hero is-success">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    Relax and enjoy your life.
                </h1>
                <h2 class="subtitle">
                    NaOne
                </h2>
            </div>
        </div>
    </section>
{% endblock %}